base: 'https://typo3-ext-dev.ddev.site/'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: English
    hreflang: en-us
    direction: ltr
    flag: us
    websiteTitle: ''
rootPageId: 1
websiteTitle: 'Typo3 Ext Dev'
